### ISSUE TITLE
Cannot define method `nodeToParentTransform'

### ISSUE THREAD

**Issue by Omnipresent** [NSCoder/Joybox-Examples#1]
Cannot define method `nodeToParentTransform' because no Objective-C stub was pre-compiled for types`{CGAffineTransform=ffffff}@:'. Make sure you properly link with the framework or library that defines this message.

I get the above error after grabbing the code, running git and then running rake.

**Comment by NSCoder** [comment]
Thanks for the report! 

Can you help me trying this on your machine:
1. Delete .repl_history
2. rake clean
3. gem uninstall -a joybox
4. gen install joybox
5. rake

I hope this will fix the problem!

Thank you :)

**Comment by Omnipresent** [comment]
Thanks! that fixed it! re-installing joybox was the key

**Comment by NSCoder** [comment]
Awesome! \o/ thanks for the report!
